// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "common": {
    "appName": "FeedbackBoard",
    "loading": "Loading…",
    "error": {
      "generic": "Something went wrong. Please try again.",
      "unauthorized": "You need to sign in to continue.",
      "notFound": "We could not find what you were looking for."
    }
  },
  "login": {
    "title": "Sign in to FeedbackBoard",
    "emailLabel": "Email address",
    "emailInvalid": "Enter a valid email address.",
    "submit": "Send magic link",
    "sending": "Sending…",
    "checkEmail": "Check {email} for a sign-in link.",
    "error": "We could not send the link. Please try again."
  },
  "publicBoard": {
    "empty": "No feedback has been posted yet.",
    "voteCount": "{count, number} votes",
    "status": {
      "OPEN": "Open",
      "PLANNED": "Planned",
      "IN_PROGRESS": "In progress",
      "DONE": "Done",
      "CLOSED": "Closed"
    },
    "category": {
      "BUG": "Bug",
      "FEATURE_REQUEST": "Feature request",
      "UX": "UX",
      "OTHER": "Other"
    },
    "priority": {
      "LOW": "Low priority",
      "MEDIUM": "Medium priority",
      "HIGH": "High priority"
    },
    "notFound": {
      "title": "Board not found",
      "description": "This board does not exist or is not public."
    }
  },
  "dashboard": {
    "title": "Your organizations",
    "empty": "You don't belong to any organization yet. Create one to get started.",
    "planBadge": {
      "FREE": "Free plan",
      "PRO": "Pro plan"
    },
    "createOrg": {
      "title": "Create an organization",
      "nameLabel": "Organization name",
      "nameInvalid": "Enter a name between 2 and 60 characters.",
      "slugLabel": "URL slug",
      "slugHelp": "Lowercase letters, numbers and hyphens. Used in your board's public URL.",
      "slugInvalid": "Enter a valid, non-reserved slug.",
      "slugReserved": "That slug is reserved. Choose another one.",
      "submit": "Create organization",
      "creating": "Creating…",
      "error": "We could not create the organization. Please try again."
    }
  }
};
export default messages;