// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "common": {
    "appName": "FeedbackBoard",
    "loading": "Loading…",
    "error": {
      "generic": "Something went wrong. Please try again.",
      "unauthorized": "You need to sign in to continue.",
      "notFound": "We could not find what you were looking for."
    }
  }
};
export default messages;